package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	carddb "github.com/FourSoulsRepo/card_db"
)

// Status is how far a card is (TS-02).
type Status int

// The statuses, from least to most done.
const (
	NotStarted  Status = iota // the file is still a stub
	Implemented               // the stub marker is gone
	Tested                    // the card also has its own test file
)

func (s Status) String() string {
	switch s {
	case Implemented:
		return "implemented"
	case Tested:
		return "tested"
	case NotStarted:
		return "not started"
	default:
		return "not started"
	}
}

// cardStatus reads the status of one card from its files in dir.
func cardStatus(dir string, ref carddb.Ref) (Status, error) {
	file := filepath.Join(dir, fileName(ref))
	src, err := os.ReadFile(file) //nolint:gosec // path is built from validated card IDs
	switch {
	case errors.Is(err, os.ErrNotExist):
		return NotStarted, nil
	case err != nil:
		return NotStarted, fmt.Errorf("cardgen: %w", err)
	case bytes.Contains(src, []byte(StubMarker)):
		return NotStarted, nil
	}
	if _, err := os.Stat(strings.TrimSuffix(file, ".go") + "_test.go"); err == nil {
		return Tested, nil
	}
	return Implemented, nil
}

// counts is one row of a summary table.
type counts [3]int

func (c counts) total() int { return c[NotStarted] + c[Implemented] + c[Tested] }

func (c counts) row(name string) string {
	return fmt.Sprintf("| %s | %d | %d | %d | %d | %d%% |\n",
		name, c.total(), c[Tested], c[Implemented], c[NotStarted], c[Tested]*100/max(c.total(), 1))
}

const tableHead = "| %s | Cards | Tested | Implemented | Not started | Tested %% |\n|---|---|---|---|---|---|\n"

// writeRows writes one summary row per key, sorted by key.
func writeRows(b *bytes.Buffer, m map[string]*counts) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	for _, k := range keys {
		b.WriteString(m[k].row(k))
	}
}

// report builds the Markdown card status report for every set in db.
// root is the folder of the set packages.
func report(db *carddb.DB, root string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("# Card status\n\n")
	b.WriteString("Generated by `go run ./cmd/cardgen -report`; do not edit.\n\n")
	b.WriteString("* Not started: the card file is still a stub.\n")
	b.WriteString("* Implemented: the stub marker is gone.\n")
	b.WriteString("* Tested: the card also has its own `_test.go` file.\n\n")

	var sets bytes.Buffer
	fmt.Fprintf(&sets, "## Sets\n\n"+tableHead, "Set")
	var detail bytes.Buffer
	for _, set := range db.Sets() {
		var all counts
		byType := map[string]*counts{}
		byKind := map[string]*counts{}
		var rows []string
		for _, ref := range db.Refs() {
			c, _ := db.Get(ref)
			if c.Set != set.Code {
				continue
			}
			st, err := cardStatus(filepath.Join(root, set.Code), ref)
			if err != nil {
				return nil, err
			}
			all[st]++
			if byType[c.Type] == nil {
				byType[c.Type] = &counts{}
			}
			byType[c.Type][st]++
			kind := strings.TrimSuffix(kinds[c.Type], "Card")
			if byKind[kind] == nil {
				byKind[kind] = &counts{}
			}
			byKind[kind][st]++
			rows = append(rows, fmt.Sprintf("| %s | `%s` | %s | %s |\n", c.Text[carddb.English].Name, ref, c.Type, st))
		}
		sets.WriteString(all.row(fmt.Sprintf("%s (`%s`)", set.Name, set.Code)))

		fmt.Fprintf(&detail, "\n## %s\n\n### By kind\n\n"+tableHead, set.Name, "Kind")
		writeRows(&detail, byKind)
		fmt.Fprintf(&detail, "\n### By printed type\n\n"+tableHead, "Type")
		writeRows(&detail, byType)
		detail.WriteString("\n### Cards\n\n| Card | Ref | Type | Status |\n|---|---|---|---|\n")
		for _, r := range rows {
			detail.WriteString(r)
		}
	}
	b.Write(sets.Bytes())
	b.Write(detail.Bytes())
	return b.Bytes(), nil
}
