// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {legal} from '../models';
import {version} from '../models';

export function Notice():Promise<Array<legal.Line>>;

export function Versions():Promise<version.Info>;
