// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Notice() {
  return window['go']['main']['App']['Notice']();
}

export function Versions() {
  return window['go']['main']['App']['Versions']();
}
